New rule: FM recommendations
abaplint/abaplint pull request #1422
Opened 2020-10-05 15:05 UTC by g-back

closes #1187

2020-10-05 17:20 UTC, larshp requested changes

2020-10-05 17:20 UTC, larshp commented on packages/core/src/rules/function_module_recommendations.ts
> +      tags: [RuleTag.Styleguide],
If its part of the ABAP style guide somewhere, please add a link under extendedInformation

2020-10-05 17:20 UTC, larshp commented on packages/core/src/rules/function_module_recommendations.ts
> +        issues.push(Issue.atToken(file, token, this.getMessage(index), this.getMetadata().key));
add severity, example: https://github.com/abaplint/abaplint/blob/198643a85378319ee368049878d182cb7a05a20c/packages/core/src/rules/begin_single_include.ts#L61

2020-10-05 18:44 UTC, FreHu commented
I'd also recommend the FM `function_exists`, it should be replaced by calling the function in a try-catch instead of checking for existence before calling. This approach is much faster assuming the function exists.

2020-10-06 07:20 UTC, larshp approved these changes

2020-10-06 07:21 UTC, larshp commented
thanks 👍

2020-10-06 07:21 UTC, merged