Fix default for local dependencies
abaplint/abaplint pull request #1610
Opened 2020-12-11 01:28 UTC by mbtools

`folder` and `files` are concatenated so it should be `/deps/**/*.*` as a default

2020-12-11 06:38 UTC, larshp commented
no, its under `/deps/src/**/*.*`,

![image](https://user-images.githubusercontent.com/5888506/101871466-e5609a00-3b83-11eb-81ec-ab58b0aca884.png)

2020-12-11 06:39 UTC, larshp requested changes
see above

2020-12-11 13:29 UTC, mbtools commented
I see. I must have uploaded to /deps/*.* manually

2020-12-11 13:29 UTC, closed without merging

2020-12-29 23:53 UTC, mbtools commented
just making a note where `loadDependencies` is located:
https://github.com/abaplint/abaplint/blob/master/packages/cli/src/cli.ts#L81