Prefer RAISE EXCEPTION NEW to RAISE EXCEPTION TYPE - new rule
abaplint/abaplint pull request #1682
Opened 2021-01-18 18:24 UTC by jan-jezek

Issue #1607

2021-01-18 18:33 UTC, larshp commented on packages/core/src/rules/prefer_raise_exception_new.ts
> +      if (statement.concatTokens().toString().toUpperCase().startsWith("RAISE EXCEPTION TYPE ")) {
concatenating all tokens is quite expensive suggest doing
`statement.get() instanceof Statements.Raise`

see example in https://github.com/abaplint/abaplint/blob/master/packages/core/src/rules/ambiguous_statement.ts

2021-01-19 08:31 UTC, g-back requested changes
Nice. Could you please add a version check? `RAISE EXCEPTION NEW` is only available from v752 onwards.
See https://github.com/abaplint/abaplint/blob/a86fd4892fb6c8fe12602dba45f4d28291c08095/packages/core/src/rules/inline_data_old_versions.ts#L35-L37 for an example.
Please also add test cases for different versions (above and below 752) - see the tests for the aforementioned rule for an example on how that works.

2021-01-19 10:07 UTC, jan-jezek commented
Now with instanceof Statements.Raise this statement is not recognized.
`RAISE EXCEPTION TYPE cx_generation_error
  EXPORTING
    previous = exception
  MESSAGE e136(messages).`
because it is instanceof Unknown, created issue #1683.

2021-01-19 10:25 UTC, g-back commented
Looks good, please add a test case where `RAISE EXCEPTION NEW` is used, then I'm happy 👍

2021-01-19 11:52 UTC, g-back approved these changes
thanks 👍

2021-01-19 12:07 UTC, larshp commented
cool, merging

2021-01-19 12:07 UTC, merged